#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus-per-node=1
#SBATCH --job-name=TrainModel
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5
#SBATCH --time=01:00:00
#SBATCH --output=test.out

module purge
module load 2023
module load Anaconda3/2023.07-2
module load FFmpeg/6.0-GCCcore-12.3.0

cd $HOME/music-generator

source activate music-generator

# export CUDA_LAUNCH_BLOCKING=1
# export TORCH_USE_CUDA_DSA=1

srun python dreambooth_musicgen.py \
    --model_name_or_path "facebook/musicgen-large" \
    --dataset_name "AndreiBlahovici/music_dataset" \
    --dataset_config_name "default" \
    --focus_genre "Electronic" \
    --output_dir "./musicgen-large-lora-electronic" \
    --text_column_name "caption" \
    --do_train \
    --num_train_epochs 2 \
    --per_device_train_batch_size 2 \
    --learning_rate 2e-4 \
    --adam_beta1 0.9 \
    --adam_beta2 0.99 \
    --weight_decay 0.1 \
    --guidance_scale 3.0 \
    --predict_with_generate \
    --include_inputs_for_metrics \
    --eval_steps 25 \
    --evaluation_strategy "epoch" \
    --per_device_eval_batch_size 1 \
    --generation_max_length 400 \
    --dataloader_num_workers 8 \
    --logging_steps 1 \
    --max_duration_in_seconds 31 \
    --min_duration_in_seconds 1.0 \
    --preprocessing_num_workers 8 \
    --pad_token_id 2048 \
    --decoder_start_token_id 2048 \
    --seed 42 \
    --overwrite_output_dir \
    --use_lora \
    --fp16